# Generated by Django 6.0.2 on 2026-06-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(choices=[('USER', 'User'), ('PROJECT', 'Project'), ('TASK', 'Task'), ('COMMENT', 'Comment')], max_length=20),
        ),
    ]
