# Generated by Django 6.0.6 on 2026-07-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Receive email notifications for task deadlines'),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_before_days',
            field=models.IntegerField(default=3, help_text='Number of days before deadline to send notification'),
        ),
    ]
